# Generated by Django 3.2.4 on 2021-08-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=12, null=True)),
                ('trainer', models.CharField(blank=True, max_length=20, null=True)),
                ('syllabus', models.FileField(null=True, upload_to='documents/%y/%m/%d')),
                ('course_code', models.CharField(blank=True, max_length=12, null=True)),
                ('coursedescription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
