from django.db import models
# Create your models here.
class Student(models.Model):
    profile_picture=models.ImageField(upload_to="images/")
    first_name=models.CharField(max_length=12)
    last_name=models.CharField(max_length=20)
    email_address=models.CharField(max_length=40)
    age=models.PositiveSmallIntegerField()
    date_of_birth=models.DateField()
    # gender_choice=((u'F',U'female'),(u'm',U'male'),(u'o','other'))
    nationality_choice=((u'k',U'Kenyan'),(u'r',U'Rwandan'),(u'u','Ugandan'),(U't','Tanzanian'),(U'a','Algerian'),(U'a','Angolan'),(U'b','Burundian'),(U'b','Burkinabe'),(U'c','Cameroonian'))
    nationality=models.CharField(max_length=20,choices=nationality_choice)
    health_status=models.CharField(max_length=50)
    city=models.CharField(max_length=30)
    State=models.CharField(max_length=30)
    class_name=models.CharField(max_length=21)
    laptop_serial_number=models.CharField(max_length=30,null=True,blank=True)
    guardian_name=models.CharField(max_length=20,null=True,blank=True)
    parent_contact=models.CharField(max_length=20)
    parent_name=models.CharField(max_length=15)
    email_address=models.CharField(max_length=40)
    phone_number=models.CharField(max_length=20,null=True,blank=True)
    passport=models.ImageField()
    # admission_date=models.DateField(null=True,blank=True)