# Generated by Django 3.2.4 on 2021-08-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('profile_picture', models.ImageField(upload_to='images/')),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=12, null=True)),
                ('contract', models.FileField(upload_to='images/')),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=19)),
                ('course_Name', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('language', models.CharField(max_length=3)),
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nationality', models.CharField(choices=[('k', 'Kenyan'), ('r', 'Rwandan'), ('u', 'Ugandan'), ('t', 'Tanzanian'), ('a', 'Algerian'), ('a', 'Angolan'), ('b', 'Burundian'), ('b', 'Burkinabe'), ('c', 'Cameroonian')], max_length=23)),
            ],
        ),
    ]
