# Generated by Django 3.2.4 on 2021-08-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(choices=[('k', 'kenya'), ('r', 'rwanda'), ('u', 'uganda')], max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('parent_contact', models.CharField(max_length=20)),
                ('parent_name', models.CharField(max_length=15)),
                ('email_address', models.CharField(max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('health_status', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(max_length=15, upload_to='')),
                ('guardian_name', models.CharField(blank=True, max_length=20, null=True)),
                ('class_name', models.CharField(max_length=21)),
                ('passport', models.ImageField(max_length=12, upload_to='')),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('laptop_serial_number', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
